name: Run Terraform

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tfremote
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run terraform
      uses: hashicorp/setup-terraform@v1
      with:
       terraform_version: 0.14.7
       terraform_wrapper: false

    - name: Git clone
      working-directory: test
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_GITHUB }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run terraform plan
      working-directory: example
      run: |
        # TF ENVIRONMENT
        cd ../example/ecs/base
        tf -cloud aws plan -var-file ../custom/sample.tfvars
      env:
        # TF ENVIRONMENT
        TF_AWS_BUCKET: terraform-remotestate-security
        TF_AWS_PROFILE: default
        TF_AWS_BUCKET_REGION: us-west-2
        # AWS CREDENTIALS
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
        AWS_SESSION_TOKEN:
        AWS_SECURITY_TOKEN:

